<a href="https://colab.research.google.com/github/Stamatics-NumberstoNeurons/assignment1-basicpythonandnumpy-sushanthnprabhu-netizen/blob/main/numpy_worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [ ]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [ ]:
# Write your code here:
print(np.__version__)

2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [ ]:
# Write your code here:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [ ]:
# Write your code here:


### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
matrix=np.full((3,3),True)
print(matrix)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
arr[arr%2==1]=-1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
a=np.where(arr%2==1,-1,arr)
print(a)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [ ]:
# Input — do not modify
arr = np.arange(10)

In [ ]:
# Write your code here:
arr=arr.reshape(2,-1)
print(arr)


[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [ ]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [ ]:
# Write your code here:
c=np.vstack((a,b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [ ]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [ ]:
# Write your code here:
c=np.hstack((a,b))
print(c)


[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [ ]:
# Input — do not modify
a = np.array([1, 2, 3])

In [ ]:
# Write your code here:
c=np.concatenate((np.repeat(a,3),np.tile(a,3)))
print(c)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [ ]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
# Write your code here:
print(np.intersect1d(a,b))


[2 4]


### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [ ]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [ ]:
# Write your code here:
print(np.setdiff1d(a,b))


[1 2 3 4]


### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [ ]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
# Write your code here:
print(np.where(a==b))


(array([1, 3, 5, 7]),)


### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [ ]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [ ]:
# Write your code here:
print(a[(a>=5)&(a<=10)])

[ 6  9 10]


### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [ ]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [ ]:
# Write your code here:
vmaxx=np.vectorize(maxx)
print(vmaxx(a,b))


[6 7 9 8 9 7 5]


### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
# Write your code here:
arr[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
# Write your code here:
arr[[0,2,1],:]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
# Write your code here:
arr[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [ ]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [ ]:
# Write your code here:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [ ]:
# Write your code here:
arr=np.random.rand(5,3)*5+5
print(arr)

[[6.429 9.262 9.875]
 [9.424 6.798 7.994]
 [6.774 6.701 5.89 ]
 [6.188 5.224 7.527]
 [6.881 7.964 8.15 ]]


### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [ ]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [ ]:
# Write your code here:
np.set_printoptions(precision=3)
print(rand_arr)

[[0.143 0.934 0.946]
 [0.602 0.388 0.363]
 [0.204 0.277 0.247]
 [0.174 0.967 0.957]
 [0.598 0.731 0.34 ]]


### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [ ]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [ ]:
# Write your code here:
np.set_printoptions(suppress=True)
print(rand_arr)

[[0.001 0.    0.   ]
 [0.001 0.    0.   ]
 [0.001 0.001 0.   ]]


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [ ]:
# Input — do not modify
a = np.arange(15)

In [ ]:
# Write your code here:
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [ ]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [ ]:
# Write your code here:
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [ ]:
# Write your code here:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
iris = np.genfromtxt(url, delimiter=',', dtype=object)
print(iris[::])


[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Ir

### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [ ]:
# Write your code here:
species = iris[:, -1]
print(species[::])

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iri

### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [ ]:
# Write your code here:
iris_2d = iris[:, :-1]
print(iris_2d[::])

[[b'5.1' b'3.5' b'1.4' b'0.2']
 [b'4.9' b'3.0' b'1.4' b'0.2']
 [b'4.7' b'3.2' b'1.3' b'0.2']
 [b'4.6' b'3.1' b'1.5' b'0.2']
 [b'5.0' b'3.6' b'1.4' b'0.2']
 [b'5.4' b'3.9' b'1.7' b'0.4']
 [b'4.6' b'3.4' b'1.4' b'0.3']
 [b'5.0' b'3.4' b'1.5' b'0.2']
 [b'4.4' b'2.9' b'1.4' b'0.2']
 [b'4.9' b'3.1' b'1.5' b'0.1']
 [b'5.4' b'3.7' b'1.5' b'0.2']
 [b'4.8' b'3.4' b'1.6' b'0.2']
 [b'4.8' b'3.0' b'1.4' b'0.1']
 [b'4.3' b'3.0' b'1.1' b'0.1']
 [b'5.8' b'4.0' b'1.2' b'0.2']
 [b'5.7' b'4.4' b'1.5' b'0.4']
 [b'5.4' b'3.9' b'1.3' b'0.4']
 [b'5.1' b'3.5' b'1.4' b'0.3']
 [b'5.7' b'3.8' b'1.7' b'0.3']
 [b'5.1' b'3.8' b'1.5' b'0.3']
 [b'5.4' b'3.4' b'1.7' b'0.2']
 [b'5.1' b'3.7' b'1.5' b'0.4']
 [b'4.6' b'3.6' b'1.0' b'0.2']
 [b'5.1' b'3.3' b'1.7' b'0.5']
 [b'4.8' b'3.4' b'1.9' b'0.2']
 [b'5.0' b'3.0' b'1.6' b'0.2']
 [b'5.0' b'3.4' b'1.6' b'0.4']
 [b'5.2' b'3.5' b'1.5' b'0.2']
 [b'5.2' b'3.4' b'1.4' b'0.2']
 [b'4.7' b'3.2' b'1.6' b'0.2']
 [b'4.8' b'3.1' b'1.6' b'0.2']
 [b'5.4' b'3.4' b'1.5' b'0.4']
 [b'5.2'

### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:
sepal_length = iris_2d[:,0].astype(float)
print(np.mean(sepal_length))
print(np.median(sepal_length))
print(np.std(sepal_length))

5.843333333333334
5.8
0.8253012917851409


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:
sepal_length = iris_2d[:,0].astype(float)
normalized = (
    (sepal_length - np.min(sepal_length)) /
    (np.max(sepal_length) - np.min(sepal_length))
)
print(normalized[::])

[0.222 0.167 0.111 0.083 0.194 0.306 0.083 0.194 0.028 0.167 0.306 0.139
 0.139 0.    0.417 0.389 0.306 0.222 0.389 0.222 0.306 0.222 0.083 0.222
 0.139 0.194 0.194 0.25  0.25  0.111 0.139 0.306 0.25  0.333 0.167 0.194
 0.333 0.167 0.028 0.222 0.194 0.056 0.028 0.194 0.222 0.139 0.222 0.083
 0.278 0.194 0.75  0.583 0.722 0.333 0.611 0.389 0.556 0.167 0.639 0.25
 0.194 0.444 0.472 0.5   0.361 0.667 0.361 0.417 0.528 0.361 0.444 0.5
 0.556 0.5   0.583 0.639 0.694 0.667 0.472 0.389 0.333 0.333 0.417 0.472
 0.306 0.472 0.667 0.556 0.361 0.333 0.333 0.5   0.417 0.194 0.361 0.389
 0.389 0.528 0.222 0.389 0.556 0.417 0.778 0.556 0.611 0.917 0.167 0.833
 0.667 0.806 0.611 0.583 0.694 0.389 0.417 0.583 0.611 0.944 0.944 0.472
 0.722 0.361 0.944 0.556 0.667 0.806 0.528 0.5   0.583 0.806 0.861 1.
 0.583 0.556 0.5   0.944 0.556 0.583 0.472 0.722 0.667 0.722 0.417 0.694
 0.667 0.667 0.556 0.611 0.528 0.444]


### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:
sepal_length = iris_2d[:,0].astype(float)
exp_vals = np.exp(sepal_length)
softmax = exp_vals / np.sum(exp_vals)
print(softmax[::])

[0.002 0.002 0.001 0.001 0.002 0.003 0.001 0.002 0.001 0.002 0.003 0.002
 0.002 0.001 0.004 0.004 0.003 0.002 0.004 0.002 0.003 0.002 0.001 0.002
 0.002 0.002 0.002 0.002 0.002 0.001 0.002 0.003 0.002 0.003 0.002 0.002
 0.003 0.002 0.001 0.002 0.002 0.001 0.001 0.002 0.002 0.002 0.002 0.001
 0.003 0.002 0.015 0.008 0.013 0.003 0.009 0.004 0.007 0.002 0.01  0.002
 0.002 0.005 0.005 0.006 0.004 0.011 0.004 0.004 0.007 0.004 0.005 0.006
 0.007 0.006 0.008 0.01  0.012 0.011 0.005 0.004 0.003 0.003 0.004 0.005
 0.003 0.005 0.011 0.007 0.004 0.003 0.003 0.006 0.004 0.002 0.004 0.004
 0.004 0.007 0.002 0.004 0.007 0.004 0.016 0.007 0.009 0.027 0.002 0.02
 0.011 0.018 0.009 0.008 0.012 0.004 0.004 0.008 0.009 0.03  0.03  0.005
 0.013 0.004 0.03  0.007 0.011 0.018 0.007 0.006 0.008 0.018 0.022 0.037
 0.008 0.007 0.006 0.03  0.007 0.008 0.005 0.013 0.011 0.013 0.004 0.012
 0.011 0.011 0.007 0.009 0.007 0.005]


### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:
sepal_length = iris_2d[:,0].astype(float)
p5 = np.percentile(sepal_length, 5)
p95 = np.percentile(sepal_length, 95)
print(p5, p95)


4.6 7.254999999999998


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:
iris_float = iris_2d.astype(float)
indices = np.random.choice(iris_float.size, 20, replace=False)
iris_float.ravel()[indices] = np.nan
print(iris_float)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 nan]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 nan]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  nan nan]
 [5.1 nan 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 nan 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:
sepal_length = iris_float[:,0]
mask = np.isnan(sepal_length)
print("Count:", np.sum(mask))
print("Positions:", np.where(mask)[0])


Count: 4
Positions: [ 78  95 131 140]


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:
filtered = iris_float[
    (iris_float[:,2] > 1.5) &
    (iris_float[:,0] < 5.0)]
print(filtered)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.5 4.5 1.7]]


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:
clean_rows = iris_float[~np.isnan(iris_float).any(axis=1)]

print(clean_rows)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [6.3 3.3 4.7 1.6]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.

### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:
sepal_length = iris_2d[:,0].astype(float)
petal_length = iris_2d[:,2].astype(float)
corr = np.corrcoef(sepal_length, petal_length)
print(corr)


[[1.    0.872]
 [0.872 1.   ]]


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:
has_nan = np.isnan(iris_float).any()
print(has_nan)


True


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:
iris_float[np.isnan(iris_float)] = 0

print(iris_float)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0. ]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0. ]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  0.  0. ]
 [5.1 0.  1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 0.  1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [ ]:
# Write your code here:
unique_vals, counts = np.unique(species, return_counts=True)
print(unique_vals)
print(counts)

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']
[50 50 50]


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:
petal_length = iris_2d[:,2].astype(float)
labels = np.where( petal_length < 3,'small',np.where(petal_length < 5, 'medium', 'large'))
print(labels[:10])

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small']


### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:
sepal_length = iris_2d[:,0].astype(float)
petal_length = iris_2d[:,2].astype(float)
volume = (np.pi * petal_length * (sepal_length ** 2)) / 3
print(volume[::])

[ 38.133  35.2    30.072  33.238  36.652  51.912  31.022  39.27   28.383
  37.715  45.804  38.604  33.778  21.299  42.273  51.035  39.697  38.133
  57.84   40.856  51.912  40.856  22.159  46.304  45.842  41.888  41.888
  42.474  39.643  37.012  38.604  45.804  42.474  44.349  37.715  31.416
  41.181  37.715  26.356  40.856  34.034  27.567  26.356  41.888  51.751
  33.778  43.58   31.022  44.124  36.652 241.17  193.019 244.3   126.711
 203.523 153.106 195.347  82.973 209.833 110.433  91.63  153.102 150.796
 183.141 118.224 206.838 147.781 144.434 181.144 128.076 174.974 155.865
 203.66  183.141 184.441 200.71  232.428 235.043 169.646 119.082 120.375
 117.208 137.388 192.265 137.413 169.646 220.941 182.878 134.644 126.711
 139.382 179.245 140.911  86.394 137.928 142.898 142.898 173.093  81.713
 139.496 249.38  179.661 311.456 232.754 256.616 399.208 113.144 351.572
 272.65  331.149 225.645 227.334 266.323 170.117 179.661 227.334 243.343
 415.992 428.41  188.496 284.185 160.917 415.992 20

### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [ ]:
# Write your code here:
species = iris[:, -1]
sampled = np.random.choice( ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'],size=10, p=[0.5, 0.25, 0.25])
print(sampled)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa']


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [ ]:
setosa_petal_lengths = iris[
    iris[:, -1] == b'Iris-setosa', 2].astype(float)
second_longest = np.unique(setosa_petal_lengths)[-2]
print(second_longest)

1.7


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:
sorted_indices = np.argsort(iris_2d[:,0].astype(float))
sorted_iris = iris_2d[sorted_indices]
print(sorted_iris[:5])

[[b'4.3' b'3.0' b'1.1' b'0.1']
 [b'4.4' b'2.9' b'1.4' b'0.2']
 [b'4.4' b'3.2' b'1.3' b'0.2']
 [b'4.4' b'3.0' b'1.3' b'0.2']
 [b'4.5' b'2.3' b'1.3' b'0.3']]


### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:
petal_length = iris_2d[:,2].astype(float)
values, counts = np.unique(petal_length, return_counts=True)
most_frequent = values[np.argmax(counts)]
print(most_frequent)

1.5


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:
petal_width = iris_2d[:,3].astype(float)
position = np.where(petal_width > 1.0)[0][0]
print(position)

50


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [ ]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [ ]:
# Write your code here:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
out = np.clip(a, 10, 30)
print(out)

[27.627 14.64  21.801 30.    10.    10.    30.    30.    10.    29.18
 30.    11.251 10.081 10.    11.765 30.    30.    10.    30.    14.43 ]


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [ ]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [ ]:
# Write your code here:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
positions = np.argsort(a)[-5:]
print(positions)


[18  7  3 10 15]


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [ ]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [ ]:
# Write your code here:
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))
counts = np.array([len(np.unique(row)) for row in arr])
print(counts)

[7 7 5 7 7 8]


### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [ ]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [ ]:
# Write your code here:
flat = np.concatenate(arr_2d)
print(flat)

[0 1 2 3 4 5 6 7 8 9]


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.